### ISSUE TITLE
Location not appearing for some solutions partners, then appears when region filtering is applied.

### ISSUE THREAD

**Issue by teeyoutan** [optimizely/marketing-website#459]
Landing page experience :+1: 
![image](https://cloud.githubusercontent.com/assets/7102310/4469173/2a2448fa-490d-11e4-8ab5-1c50063d51b0.png)

filter applied:
![image](https://cloud.githubusercontent.com/assets/7102310/4469179/35d9f91a-490d-11e4-92f9-09499362fef6.png)

Filter removed:

![image](https://cloud.githubusercontent.com/assets/7102310/4469182/42757c9e-490d-11e4-99a7-1102a70da938.png)

Notice missing locations....

**Comment by bhamodi** [comment]
No longer valid. Closing this issue now.
