### ISSUE TITLE
General Mobile Page QA Issues

### ISSUE THREAD

**Issue by dtothefp** [optimizely/marketing-website#583]
Logged by Marco Sgrignuoli:  #visual-changes-demo slightly overlapping #visual-change-options
(cannot reproduce)

![screen shot 2014-10-31 at 1 47 53 pm](https://cloud.githubusercontent.com/assets/4656726/4865733/1ffee9ee-6126-11e4-9420-903d02ddff4d.png)

Logged by Byron Jones: when my chrome browser was sized at 1375x640, there appears to be some framing that shows on option B
(cannot reproduce)

![screen shot 2014-10-30 at 5 30 57 pm](https://cloud.githubusercontent.com/assets/4656726/4865754/46449248-6126-11e4-8efa-a8709673b45d.png)

Logged by  Yonatan Kogan:  The text of the button also doesn't reset if you delete all your custom text
(able to reproduce)

### Before entering text
![screen shot 2014-10-31 at 1 51 31 pm](https://cloud.githubusercontent.com/assets/4656726/4865779/928f2546-6126-11e4-96a9-d2db7998ceee.png)

### After entering and deleting text
![screen shot 2014-10-31 at 1 51 39 pm](https://cloud.githubusercontent.com/assets/4656726/4865782/9d5ce94a-6126-11e4-89d0-77ceec5beeb0.png)

**Comment by bhamodi** [comment]
All done. :+1:
