### ISSUE TITLE
Hipmunk photo/modal on /mobile a bit wonky

### ISSUE THREAD

**Issue by blindquist12** [optimizely/marketing-website#623]
On the /mobile page, on the hipmunk modal where visitors can toggle between variations, one of the photos isn't quite lined up properly and looks a bit strange/broken when that variation is selected (see screenshot below)
![screen shot 2014-11-11 at 1 19 21 pm](https://cloud.githubusercontent.com/assets/8672450/5001620/89d1c4ac-69ac-11e4-8909-da2a12e36e69.png)

**Comment by bhamodi** [comment]
No longer valid.
