### ISSUE TITLE
Mobile signup page lead capture is broken

### ISSUE THREAD

**Issue by yesplease** [optimizely/marketing-website#631]
On my iphone, I navigated to optimizely.com/mobile. I clicked the main big green CTA "Sign up" and was not brought to the appropriate page (it was a signin page instead of a form). Pics below.

I clicked from here:
![img_3087](https://cloud.githubusercontent.com/assets/7796339/5016495/8abcb980-6a5b-11e4-9c2b-432e5c3ae9b9.jpg)

And was brought here: 
![img_3088](https://cloud.githubusercontent.com/assets/7796339/5016499/901dcf18-6a5b-11e4-92f9-fe4b8c82e479.jpg)

**Comment by bhamodi** [comment]
This is no longer valid. Closing. :+1:
