### ISSUE TITLE
Typo/font issue on new /mobile page (staging version)

### ISSUE THREAD

**Issue by KarenLoughrey** [optimizely/marketing-website#633]
Hi,

On the new /mobile page, currently in staging, there are 2 'f's missing from the word 'different' - under the 'Inputs and Interactions' header.
![2014-11-13_1414](https://cloud.githubusercontent.com/assets/8735984/5028775/ae0cedc6-6b3f-11e4-8e88-a02d655ebc54.png)

**Comment by dtothefp** [comment]
@KarenLoughrey this doesn't help me unless I know the branch of staging you are talking about. Please include a full url

**Comment by KarenLoughrey** [comment]
@dtothefp This was a comment from Nov 2014 while we were working on MVPP. No longer relevant.
