### ISSUE TITLE
Platform checkbox isn't checked on label click

### ISSUE THREAD

**Issue by 4vanger** [optimizely/marketing-website#703]
- go to https://www.optimizely.com
- click "sign up" in top-right
- click on label "Web"/"Mobile Web"/"IOS"/"Android" in "Channels I'd like to test" section 
Expected result: corresponding checkbox should be toggled. If I click on "Mobile Web" label - I expect to toggle second checkbox. 
Actual result: Any of checkboxes isn't toggled

**Comment by bhamodi** [comment]
No longer valid. The checkboxes work properly. :+1:
