### ISSUE TITLE
Hover text on pricing page doesn't move with mouse cursor

### ISSUE THREAD

**Issue by seanoliver** [optimizely/marketing-website#866]
When I hover over text on the pricing page, the hover help text remains on the first line item you over on even after the cursor moves on to the next item in the list. Ideally, the hover text would disappear on mouse exit so that you can see the help text for each one as you hover down the list:
![screen shot 2015-02-19 at 12 26 21 pm](https://cloud.githubusercontent.com/assets/882952/6275297/caae673a-b832-11e4-95ec-091dc8a9a16d.png)

**Comment by dtothefp** [comment]
@seanoliver this is desired behavior, the tooltip only closes when the user clicks outside of it. This is better UX in my opinion because having to hover to read something is annoying. Also, there are no hover events in mobile so better it stays open until the user clicks off.
